name: Testing the GitHub Pages publication

on:
  push:
    branches:
      - master
    
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: copy metadata for gauge <= 1.0.8
      run: for f in *.json; do [[ -e $f ]] || continue; cp $f "${f%-install.json}"; done

    - uses:  helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}